@extends('layouts.app')

@section('title', 'Pradžia')

@section('content')
    <div>
        <img src="/img/alien.jpg" alt="alien_image" class="alien-image py-4">

        <h1>Kompiuteriniai Žaidimai</h1>

        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
        
        <h1>Istorija</h1>

        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequatur perspiciatis reprehenderit quisquam iusto tempora. Necessitatibus accusantium odit similique natus omnis doloremque harum eligendi totam in quisquam, non, accusamus saepe tenetur distinctio? Praesentium unde molestias placeat enim quaerat accusamus odio dicta sunt adipisci, ipsam quo eveniet! Delectus praesentium iusto facere nihil quo, aut, ex sit corrupti perspiciatis neque assumenda sint alias, nesciunt totam aliquam? Debitis fugiat, odit, assumenda a, commodi sapiente praesentium autem maxime nisi eius velit ipsum molestias architecto quam! Eum voluptatibus cupiditate quo exercitationem, repellat minima porro eos sint velit, laborum ad officia nostrum numquam reiciendis. Delectus, harum. Consequuntur.</p>
    </div>

    <div>
        <img src="/img/gaming_banner.png" alt="rog" class="rog">
    </div>
@endsection